SELECT EMPNO, ENAME, LOWER(ENAME),
       HIREDATE, TO_CHAR(HIREDATE, 'YYYY')
FROM EMP;


SELECT SUM(SAL), AVG(SAL), MAX(SAL), MIN(SAL), COUNT(SAL)
FROM EMP ; 

SELECT AVG(ENAME)
FROM EMP;

SELECT SUM(HIREDATE)
FROM EMP; --날짜는 덧셈 불가능

SELECT MIN(ENAME), MIN(HIREDATE), MAX(HIREDATE)
FROM EMP; -- MIN MAX 는 숫자 날짜의 제한을 받지 않는다.

SELECT COUNT(*)
FROM EMP; --컬럼의갯수를 카운트, *을 사용할수있는함수

SELECT COUNT(*), COUNT(ENAME), COUNT(EMPNO), COUNT(HIREDATE)
FROM EMP;

SELECT COUNT(*), COUNT(ENAME), COUNT(EMPNO), COUNT(HIREDATE)
FROM EMP
WHERE DEPTNO =10;

SELECT COUNT(*), COUNT(EMPNO), COUNT(COMM)
FROM EMP ; --NULL 제외하고 카운트

SELECT COUNT(*), COUNT(EMPNO), COUNT(COMM), COUNT(MGR)
FROM EMP ; 

SELECT COUNT(COMM)
FROM EMP 
WHERE COMM IS NULL ; 

SELECT *
FROM EMP
WHERE COMM IS NULL;

SELECT COUNT(EMPNO)
FROM EMP 
WHERE COMM IS NULL ; 

SELECT SUM(COMM)/14, AVG(COMM)
FROM EMP;

SELECT SUM(COMM)/4, AVG(COMM)
FROM EMP ;

SELECT SUM(COMM)/14, AVG(NVL(COMM,0))
FROM EMP ;

SELECT COUNT(NVL(COMM,0)), COUNT(*)
FROM EMP 
WHERE COMM IS NULL ; 

SELECT DEPTNO 
FROM EMP ; 

SELECT DISTINCT DEPTNO 
FROM EMP ;

SELECT COUNT(DEPTNO), COUNT(DISTINCT DEPTNO)
FROM EMP ; 

SELECT SUM(ALL DEPTNO), SUM(DISTINCT DEPTNO)
FROM EMP ; 

----------------------------------------------------
SELECT SUM(SAL)
FROM EMP
WHERE DEPTNO =10;

SELECT SUM(SAL)
FROM EMP
WHERE DEPTNO =20;

SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'MANAGER';

SELECT DEPTNO, SAL 
FROM EMP
ORDER BY DEPTNO;

SELECT JOB, SAL
FROM EMP
ORDER BY JOB;

SELECT DEPTNO, SUM(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO , SUM(SAL), AVG(SAL),
       MIN(SAL), MAX(SAL), MIN(HIREDATE), COUNT(*)
FROM EMP 
GROUP BY DEPTNO ; 

SELECT DEPTNO, JOB, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO ; --오류나는 이유: 행갯수가 맞지않아서

SELECT SUM(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, SUM(SAL)
FROM EMP
GROUP BY DEPTNO, JOB; --이렇게해야 행갯수가 맞는다.

SELECT TO_CHAR(HIREDATE,'YYYY'), SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'); --맞는답

SELECT HIREDATE, SUM(SAL)
FROM EMP 
GROUP BY HIREDATE ; 

SELECT TO_CHAR(HIREDATE,'YYYY'), SUM(SAL)
FROM EMP 
GROUP BY HIREDATE ; --그룹만들떄 년도만 뽑았으면 보여줄 HIREDATE는 없다., 
                                    --꼭 컬럼의 이름만 들어올 필요는없다.


SELECT HIREDATE, SUM(SAL)  -- ERROR 
FROM EMP 
GROUP BY TO_CHAR(HIREDATE,'YYYY')  ; 
 
--------------------------------------------------------------------

SELECT DEPTNO, SUM(SAL)
FROM EMP
WHERE SUM(SAL)>5000
GROUP BY DEPTNO; --순서상 1.FROM 2. WHERE 에서는 GROUP함수 불가능, 아직 GROUP이 생성되기전이라 
                 --WHERE절에는 그룹함수를 사용할수없다.
                 

--------------------------------------------------------------------
--HAVING 절은 GROUP이 만들어진 다음에사용하는 함수

SELECT DEPTNO, SUM(SAL), AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING SUM(SAL)>9000;

SELECT DEPTNO, SUM(SAL) 
FROM EMP 
HAVING SUM(SAL) > 9000 
GROUP BY DEPTNO 
; 

SELECT JOB_ID, SUM(SALARY) PAYROLL
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%REP%'
GROUP BY JOB_ID
HAVING SUM(SALARY) > 13000
ORDER BY SUM(SALARY);

------------------------------------------------
SELECT DEPTNO, SUM(SAL)
FROM EMP 
WHERE DEPTNO IN (10,20) 
GROUP BY DEPTNO 
HAVING SUM(SAL) > 10000 ;  

SELECT DEPTNO, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO 
HAVING SUM(SAL) > 10000 
   AND DEPTNO IN (10,20) ; 
--항상 동일한 결과가 나오는 두 문장
--1.FROM절, 2. GROUP BY 3. HAVING, 4. SELECT
--아래거는 불필요한 그루핑이생김

SELECT DEPTNO, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO 
HAVING SUM(SAL) > 10000 
   AND JOB IN ('SALESMAN','MANAGER') ; 
--JOB은 그룹바이가 사용되지않음

SELECT DEPTNO, SUM(SAL)
FROM EMP 
WHERE JOB IN ('SALESMAN','MANAGER')
GROUP BY DEPTNO 
HAVING SUM(SAL) > 5000; 

SELECT SUM(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT MAX(SUM(SAL))
FROM EMP
GROUP BY DEPTNO;

SELECT COUNT(MAX(SUM(SAL))) -- ERROR 
FROM EMP 
GROUP BY DEPTNO ;  --단일함수는 그룹당 한번씩 실행 

--부서별 직무별 급여의 합을 다음과 같이 검색

SELECT DEPTNO, JOB, SUM(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO ASC, JOB;

SELECT deptno
      ,SUM(DECODE(job,'ANALYST'  , sal)) AS analyst 
      ,SUM(DECODE(job,'CLERK'    , sal)) AS clerk 
      ,SUM(DECODE(job,'MANAGER'  , sal)) AS manager
      ,SUM(DECODE(job,'PRESIDENT', sal)) AS president
      ,SUM(DECODE(job,'SALESMAN' , sal)) AS salesman
FROM emp 
GROUP BY deptno 
ORDER BY deptno ;

SELECT deptno
      ,SUM(CASE WHEN job = 'ANALYST'   THEN sal END) AS analyst 
      ,SUM(CASE WHEN job = 'CLERK'     THEN sal END) AS clerk 
      ,SUM(CASE WHEN job = 'MANAGER'   THEN sal END) AS manager
      ,SUM(CASE WHEN job = 'PRESIDENT' THEN sal END) AS president
      ,SUM(CASE WHEN job = 'SALESMAN'  THEN sal END) AS salesman
FROM emp 
GROUP BY deptno 
ORDER BY deptno ; 

SELECT SUM(CASE DEPTNO WHEN 10 THEN SAL END),
       SUM(CASE DEPTNO WHEN 20 THEN SAL END), 
       SUM(CASE DEPTNO WHEN 30 THEN SAL END)
FROM EMP ; 

SELECT (CASE DEPTNO WHEN 10 THEN SUM(SAL) END),
       (CASE DEPTNO WHEN 20 THEN SUM(SAL) END), 
       (CASE DEPTNO WHEN 30 THEN SUM(SAL) END)
FROM EMP ;  --ERROR

SELECT JOB, SUM(CASE DEPTNO WHEN 10 THEN SAL END), 
       SUM(CASE DEPTNO WHEN 20 THEN SAL END), 
       SUM(CASE DEPTNO WHEN 30 THEN SAL END)
FROM EMP 
GROUP BY JOB ; 

SELECT * 
FROM EMP ; 


SELECT DEPTNO, JOB, SUM(SAL)
FROM EMP 
GROUP BY DEPTNO, JOB ; 

SELECT *
FROM SH.SALES;


SELECT CHANNEL_ID, PROD_ID, SUM(AMOUNT_SOLD)
FROM SH.SALES 
GROUP BY CHANNEL_ID, PROD_ID ; 
---------------------------------------------------
-- #CH7

SELECT *
FROM EMP
WHERE EMPNO = 7788;

SELECT *
FROM DEPT
WHERE DEPTNO = 20;

 
SELECT *
FROM EMP , DEPT 
WHERE EMPNO = 7788 ;

SELECT *
FROM EMP, DEPT
ORDER BY 1;
-- 14*4= 56 개가 검색

SELECT *
FROM DEPT;

SELECT *
FROM EMP;


SELECT *
FROM EMP, DEPT
WHERE EMPNO =7788
  AND EMP.DEPTNO = DEPT.DEPTNO;
  
SELECT *
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

CREATE TABLE EMP2 
AS 
SELECT EMP.*, DNAME, LOC  
FROM EMP , DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO ;


SELECT * FROM EMP2
WHERE EMPNO = 7788;


SELECT *
FROM EMP, DEPT
ORDER BY 1;


SELECT * 
FROM EMPLOYEES 
    ,DEPARTMENTS 
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID  ;

SELECT * 
FROM EMPLOYEES   E 
    ,DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  ;

