--1229

--6장 서브쿼리를 사용하여 데이터검색 연습문제

--1

SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM   EMPLOYEES
WHERE  (SALARY, DEPARTMENT_ID) IN 
        (SELECT SALARY, DEPARTMENT_ID
          FROM EMPLOYEES
         WHERE COMMISSION_PCT IS NOT NULL);
         
         
--2
SELECT E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY
  FROM  EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
   AND (SALARY, JOB_ID) IN (SELECT E.SALARY, E.JOB_ID
                              FROM EMPLOYEES E JOIN DEPARTMENTS D
                                                 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                                                 AND D.LOCATION_ID = 1700);
                                                 
--3
SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE (SALARY, MANAGER_ID) IN (SELECT SALARY, MANAGER_ID
                                FROM EMPLOYEES
                                WHERE LAST_NAME = 'Kochhar')
AND LAST_NAME <> 'Kochhar';

--4 
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY 
                FROM EMPLOYEES
                WHERE JOB_ID = 'SA_MAN')
                ORDER BY SALARY DESC;
                
--5
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM DEPARTMENTS
                         WHERE LOCATION_ID IN (SELECT LOCATION_ID
                                                FROM  LOCATIONS
                                                WHERE CITY LIKE 'T%'));
                                                
--6

SELECT E.LAST_NAME ENAME, E.SALARY SALARY,
       E.DEPARTMENT_ID DEPTNO, ROUND(AVG(A.SALARY),2) DPET_AVG
  FROM EMPLOYEES E, EMPLOYEES A 
  WHERE E.DEPARTMENT_ID = A.DEPARTMENT_ID
    AND E.SALARY > (SELECT AVG(SALARY)
                      FROM EMPLOYEES
                     WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)
  GROUP BY E.LAST_NAME, E.SALARY, E.DEPARTMENT_ID
  ORDER BY AVG(A.SALARY);
  
  
--7(A)
SELECT E.LAST_NAME
FROM EMPLOYEES E
WHERE NOT EXISTS( SELECT 'X'
                    FROM EMPLOYEES A
                   WHERE A.MANAGER_ID = E.EMPLOYEE_ID); 

SELECT A.LAST_NAME
  FROM EMPLOYEES A
 WHERE A.EMPLOYEE_ID
NOT IN (SELECT E.MANAGER_ID
        FROM EMPLOYEES E);
        
--8
SELECT LAST_NAME
  FROM EMPLOYEES E
 WHERE E.SALARY < (SELECT AVG(A.SALARY)
                    FROM EMPLOYEES A
                   WHERE A.DEPARTMENT_ID = E.DEPARTMENT_ID);
                   

--9
SELECT LAST_NAME
  FROM EMPLOYEES E
 WHERE EXISTS (SELECT 'X'
                FROM EMPLOYEES A
                WHERE A.DEPARTMENT_ID = E.DEPARTMENT_ID
                  AND A.HIRE_DATE > E.HIRE_DATE
                  AND A.SALARY    > E.SALARY);
                  
--10
SELECT EMPLOYEE_ID , LAST_NAME,
      (SELECT DEPARTMENT_NAME
        FROM DEPARTMENTS D
       WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) DEPARTMENT
FROM EMPLOYEES E
ORDER BY DEPARTMENT;

--11
WITH
SUMMARY AS (SELECT D.DEPARTMENT_NAME, SUM(E.SALARY) AS DEPT_TOTAL
            FROM EMPLOYEES E JOIN DEPARTMENTS D
                               ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                               GROUP BY D.DEPARTMENT_NAME)
SELECT DEPARTMENT_NAME, DEPT_TOTAL
  FROM SUMMARY
 WHERE DEPT_TOTAL > (SELECT SUM(DEPT_TOTAL) *1/8
                      FROM SUMMARY)
ORDER BY DEPT_TOTAL DESC;                      